---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tethys-ui
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tethys-ui
  template:
    metadata:
      labels:
        app: tethys-ui
    spec:
      containers:
      - name: tethys-ui
        imagePullPolicy: Always
        image: $REGISTRY/$PROJECT/$IMAGENAME:$TAGS
        ports:
        - containerPort: 80
          name: http
      restartPolicy: Always
      imagePullSecrets:
      - name: cc-harbor06
---
apiVersion: v1
kind: Service
metadata:
  name: tethys-ui
  namespace: $NAMESPACE
spec:
  type: ClusterIP
  selector:
    app: tethys-ui
  ports:
  - port: 80
    name: http